### ISSUE TITLE
Love it but

### ISSUE THREAD

**Issue by thecrazy** [Geri-Borbas/VSCode.Extension.eppz_Code#17]
I love it but to me the color scheme is horrible. I'm a monokai guy. Really wish the colors could be changed.

**Comment by rediffusion** [comment]
What is your problem? This theme has good colors. If you want you can set tons of other `2835 themes`.

**Comment by Hexodus** [comment]
I just happend to stumble uppon your theme. Even if doesen't say it directly (and could express it in a nicer way) I understand the point. Monokai is a high contrast & high saturation theme. I love your general idea but if you're used to monokai contrast and colors you'll have hard time because the code is harder to read. I also would love to see your theme with higher saturation. 

Comparision with Monokai
![Eppz_Theme](https://user-images.githubusercontent.com/243039/72687152-73124180-3afb-11ea-9ecd-b26c1855732e.jpg)

This is how higher saturation would help a lot. Then it would be on par with Monokai.
![Eppz_Theme_Saturation](https://user-images.githubusercontent.com/243039/72687161-8de4b600-3afb-11ea-8a39-ab87a1483d59.jpg)

**Comment by thecrazy** [comment]
Sorry for the "Horrible" comment didn't mean to offend. It's just hard to see the code with all those dark colours over dark background. PLUS with all the years I've been using monokai, the colours are hardwired in my brain. I tried using other themes multiple times but the loss of productivity is not worth it. This is why I wish we could customize the colours.

**Comment by rediffusion** [comment]
@thecrazy 

✋ If you have problems with `Syntax Highlighting` you can customize it here:

> C:\Users\My_PC\.vscode\extensions\eppz.eppz-code-1.2.41\themes\default\

> eppz-code.json.json
> eppz-code.markdown.json
> eppz-code.regions.attribute.json
> eppz-code.regions.comment.block.documentation.json
> eppz-code.regions.namespace.declaration.json
> eppz-code.regions.using.json
> eppz-code.root.json

 Cheers! 🌞

**Comment by Geri-Borbas** [comment]
I recommend applying filters to the [**color matrix PSD**](https://github.com/eppz/VSCode.Extension.eppz_Code/blob/master/Documents/Design/eppz!%20Code%20(default).psd), then you can pick color from there to override swatches in [theme](https://github.com/eppz/VSCode.Extension.eppz_Code/tree/master/themes/default) folder.
